# Generated by Django 4.2.1 on 2023-05-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_books_cover"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
    ]
